services:
  web:
    # build images
    build:
      context: .
      dockerfile: Dockerfile
    # image: flask
    image: flask_web:latest
    # container name
    container_name: flask_web
    # mount volumes
    volumes:
      - .:/code
    # exposed port
    ports:
      - "5000:5000"
    # set environment variables
    environment:
      - FLASK_APP=src.program:app
      - FLASK_ENV=production
    # run command
    command: flask run --host=0.0.0.0